language: python
python:
  - "3.8"
  - "3.8-dev"
  - "3.11"
  - "pypy"
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install -r requirements.test.txt -c constraints.txt
# command to run tests
script: pytest
branches:
  only:
    - master